
-- Inserção do usuário
INSERT INTO usuario (nome, email, senha) VALUES
('nome_do_usuario', 'email_do_usuario@gmail.com', 'senha_do_usuario');

INSERT INTO classificacao_etaria (codigo, descricao) VALUES
('G', 'Geral - Todos os públicos.'),
('PG', 'Pode conter algum material não adequado para crianças pequenas.'),
('PG-13', 'Filme adequado para maiores de 13 anos.'),
('R', 'Restrito - Menores de 17 anos devem estar acompanhados por um adulto.'),
('NC-17', 'Adultos somente - Não é adequado para menores de 17 anos.');

-- Inserção dos tipos de conteúdo
-- Inserção de todos os tipos conhecidos
INSERT INTO tipos (nome) VALUES
('Filme'),
('Série'),
('Dorama'),
('Anime'),
('Cartoon'),
('Documentário'),
('Minissérie'),
('Novela'),
('Reality Show'),
('Talk Show'),
('Game Show'),
('Show de Variedades'),
('Documentário de TV'),
('Web Série'),
('Curta-metragem'),
('Longa-metragem'),
('Animação Infantil'),
('Animação Adulta'),
('Animação Japonesa'),
('Animação Ocidental');

-- Inserção dos gêneros de conteúdo
INSERT INTO generos (nome) VALUES
('Ação'),
('Animação'),
('Aventura'),
('Biografia'),
('Comédia'),
('Comédia Romântica'),
('Crime'),
('Documentário'),
('Drama'),
('Família'),
('Fantasia'),
('Ficção Científica'),
('Guerra'),
('Histórico'),
('Musical'),
('Mistério'),
('Policial'),
('Romance'),
('Suspense'),
('Terror'),
('Thriller'),
('Western'),
('Nacional'),
('Estrangeiro'),
('Outro');

-- Inserção de exemplos de países
-- Inserção de todos os países do mundo
INSERT INTO pais (nome) VALUES
('Afeganistão'),
('África do Sul'),
('Albânia'),
('Alemanha'),
('Andorra'),
('Angola'),
('Antígua e Barbuda'),
('Arábia Saudita'),
('Argélia'),
('Argentina'),
('Armênia'),
('Austrália'),
('Áustria'),
('Azerbaijão'),
('Bahamas'),
('Bangladesh'),
('Barbados'),
('Barém'),
('Bélgica'),
('Belize'),
('Benin'),
('Bielorrússia'),
('Bolívia'),
('Bósnia e Herzegovina'),
('Botsuana'),
('Brasil'),
('Brunei'),
('Bulgária'),
('Burkina Faso'),
('Burundi'),
('Butão'),
('Cabo Verde'),
('Camboja'),
('Camarões'),
('Canadá'),
('Catar'),
('Cazaquistão'),
('Chade'),
('Chile'),
('China'),
('Chipre'),
('Colômbia'),
('Comores'),
('Congo-Brazzaville'),
('Coreia do Norte'),
('Coreia do Sul'),
('Cosovo'),
('Costa do Marfim'),
('Costa Rica'),
('Croácia'),
('Cuba'),
('Dinamarca'),
('Djibuti'),
('Dominica'),
('Egito'),
('Emirados Árabes Unidos'),
('Equador'),
('Eritreia'),
('Eslováquia'),
('Eslovênia'),
('Espanha'),
('Estados Unidos'),
('Estônia'),
('Etiópia'),
('Fiji'),
('Filipinas'),
('Finlândia'),
('França'),
('Gabão'),
('Gâmbia'),
('Gana'),
('Geórgia'),
('Granada'),
('Grécia'),
('Guatemala'),
('Guiana'),
('Guiné'),
('Guiné Equatorial'),
('Guiné-Bissau'),
('Haiti'),
('Honduras'),
('Hungria'),
('Iêmen'),
('Ilhas Marshall'),
('Ilhas Salomão'),
('Índia'),
('Indonésia'),
('Irã'),
('Iraque'),
('Irlanda'),
('Islândia'),
('Israel'),
('Itália'),
('Jamaica'),
('Japão'),
('Jordânia'),
('Kiribati'),
('Kuwait'),
('Laos'),
('Lesoto'),
('Letônia'),
('Líbano'),
('Libéria'),
('Líbia'),
('Liechtenstein'),
('Lituânia'),
('Luxemburgo'),
('Macedônia do Norte'),
('Madagáscar'),
('Malásia'),
('Malauí'),
('Maldivas'),
('Mali'),
('Malta'),
('Marrocos'),
('Maurício'),
('Mauritânia'),
('México'),
('Micronésia'),
('Moçambique'),
('Moldávia'),
('Mônaco'),
('Mongólia'),
('Montenegro'),
('Namíbia'),
('Nauru'),
('Nepal'),
('Nicarágua'),
('Níger'),
('Nigéria'),
('Noruega'),
('Nova Zelândia'),
('Omã'),
('Países Baixos'),
('Palau'),
('Panamá'),
('Papua Nova Guiné'),
('Paquistão'),
('Paraguai'),
('Peru'),
('Polônia'),
('Portugal'),
('Quênia'),
('Quirguistão'),
('Reino Unido'),
('República Centro-Africana'),
('República Democrática do Congo'),
('República Dominicana'),
('República Tcheca'),
('Romênia'),
('Ruanda'),
('Rússia'),
('Samoa'),
('San Marino'),
('Santa Lúcia'),
('São Cristóvão e Neves'),
('São Tomé e Príncipe'),
('São Vicente e Granadinas'),
('Senegal'),
('Sérvia'),
('Seychelles'),
('Serra Leoa'),
('Singapura'),
('Síria'),
('Somália'),
('Sri Lanka'),
('Suazilândia'),
('Sudão'),
('Sudão do Sul'),
('Suécia'),
('Suíça'),
('Suriname'),
('Tailândia'),
('Taiwan'),
('Tajiquistão'),
('Tanzânia'),
('Timor-Leste'),
('Togo'),
('Tonga'),
('Trinidad e Tobago'),
('Tunísia'),
('Turcomenistão'),
('Turquia'),
('Tuvalu'),
('Ucrânia'),
('Uganda'),
('Uruguai'),
('Uzbequistão'),
('Vanuatu'),
('Vaticano'),
('Venezuela'),
('Vietnã'),
('Zâmbia'),
('Zimbábue');
